#! /bin/sh

sxhkd &
xmodmap ~/.escToCaps &
~/.config/monitorsConfig.sh
nitrogen --restore &
xrdb ~/.config/Xresources &
~/.config/bar/bar.sh | lemonbar HDMI-1 -f Inconsolata -f FontAwesome -g 1900x32+10+10 &
compton --config ~/.config/compton.conf &

bspc config -m HDMI-1 top_padding 42	
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X
